# Generated by Django 3.1 on 2020-10-31 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='desc',
        ),
    ]
