# Generated by Django 3.1 on 2020-10-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvk', '0002_remove_feedback_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='patient',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.TextField(),
        ),
    ]
